import { test, expect, request } from '@playwright/test';
import { statistics, addDays, dateKey } from '../src/app/journal';
import { passwordProof } from '../src/app/password-proof';
const headers = {'X-Tracks-Request':'1'};
const password = 'Test-Journal-Strong-42!';
const today = dateKey(new Date());
test('calendar streaks handle gaps, multiple activities, leap days, and yesterday',()=>{
  const activity = (date:string) => ({id:date,projectId:'track',date,title:'Activity',description:'',value:null,unit:null,createdAt:date});
  expect(addDays('2024-03-01',-1)).toBe('2024-02-29');
  expect(statistics(['2024-02-27','2024-02-28','2024-02-29','2024-02-29'].map(activity),'2024-03-01')).toEqual({activeDays:3,total:4,current:3,longest:3});
  expect(statistics(['2024-02-27','2024-02-29'].map(activity),'2024-03-02').current).toBe(0);
  expect(statistics([],today)).toEqual({activeDays:0,total:0,current:0,longest:0});
});
test('API enforces ownership, validation, CSRF, and share lifecycle',async({baseURL})=>{
  const a=await request.newContext({baseURL,extraHTTPHeaders:headers});
  const b=await request.newContext({baseURL,extraHTTPHeaders:headers});
  const visitor=await request.newContext({baseURL});
  for(const [i,client] of [a,b].entries()){
    const email=`api-${Date.now()}-${i}@example.com`;
    const challengeResponse=await client.post('/api/auth/challenge',{data:{email,mode:'register'}});expect(challengeResponse.status()).toBe(200);
    const challenge=await challengeResponse.json();
    const res=await client.post('/api/auth/register',{data:{name:'Test '+i,email,proof:await passwordProof(password,challenge),ticket:challenge.ticket}});expect(res.status()).toBe(200);
    await client.post('/api/auth/logout');
    const loginChallenge=await(await client.post('/api/auth/challenge',{data:{email,mode:'login'}})).json();
    const login=await client.post('/api/auth/login',{data:{email,proof:await passwordProof(password,loginChallenge),ticket:loginChallenge.ticket}});expect(login.status()).toBe(200);
  }
  expect((await visitor.get('/api/projects')).status()).toBe(401);
  const created=await a.post('/api/projects',{data:{name:'Running',description:'Fresh air',icon:'↗',color:'blue',archived:false}});
  expect(created.status()).toBe(201);const track=await created.json();
  expect((await a.post('/api/projects',{headers:{'X-Tracks-Request':''},data:{}})).status()).toBe(403);
  expect((await b.put('/api/projects/'+track.id,{data:{...track,name:'Stolen'}})).status()).toBe(404);
  expect((await b.get('/api/projects/'+track.id+'/activities')).status()).toBe(404);
  const input={date:today,title:'Morning run',description:'Private notes',value:3,unit:'km'};
  expect((await a.post(`/api/projects/${track.id}/activities`,{data:{...input,value:-2}})).status()).toBe(400);
  const activity=await (await a.post(`/api/projects/${track.id}/activities`,{data:input})).json();
  expect((await b.put('/api/activities/'+activity.id,{data:input})).status()).toBe(404);
  expect((await b.delete('/api/activities/'+activity.id)).status()).toBe(404);
  expect((await b.post(`/api/projects/${track.id}/share`,{data:{}})).status()).toBe(404);
  let graph=await (await a.get(`/api/projects/${track.id}/heatmap?year=${today.slice(0,4)}`)).json();
  expect(graph.find((d:any)=>d.date===today).count).toBe(1);
  expect((await a.put('/api/activities/'+activity.id,{data:{...input,title:'Evening run',value:5}})).status()).toBe(200);
  const share=await (await a.post(`/api/projects/${track.id}/share`,{data:{expiresAt:null}})).json();
  const publicData=await (await visitor.get('/api/shared/'+share.token)).json();
  expect(publicData.track.name).toBe('Running');expect(publicData.track.userId).toBeUndefined();expect(publicData.activities[0].value).toBe(5);
  expect((await visitor.post(`/api/projects/${track.id}/activities`,{headers,data:input})).status()).toBe(401);
  const second=await (await a.post(`/api/projects/${track.id}/share`,{data:{}})).json();
  expect((await visitor.get('/api/shared/'+share.token)).status()).toBe(404);
  expect((await visitor.get('/api/shared/'+second.token)).status()).toBe(200);
  await a.delete(`/api/projects/${track.id}/share`);
  expect((await visitor.get('/api/shared/'+second.token)).status()).toBe(404);
  expect((await a.post(`/api/projects/${track.id}/share`,{data:{expiresAt:'2000-01-01T00:00:00Z'}})).status()).toBe(400);
  const expiring=await(await a.post(`/api/projects/${track.id}/share`,{data:{expiresAt:new Date(Date.now()+1500).toISOString()}})).json();
  await expect.poll(async()=>(await visitor.get('/api/shared/'+expiring.token)).status(),{timeout:5000}).toBe(404);
  await a.delete('/api/projects/'+track.id);
  expect((await a.post(`/api/projects/${track.id}/activities`,{data:input})).status()).toBe(400);
  expect((await a.get(`/api/projects/${track.id}/activities`)).status()).toBe(200);
  await a.put('/api/projects/'+track.id,{data:{...track,archived:false}});
  await a.delete('/api/activities/'+activity.id);
  graph=await(await a.get(`/api/projects/${track.id}/heatmap?year=${today.slice(0,4)}`)).json();expect(graph.find((d:any)=>d.date===today).count).toBe(0);
  await a.post('/api/auth/logout');expect((await a.get('/api/projects')).status()).toBe(401);
  await a.dispose();await b.dispose();await visitor.dispose();
});
test('journal UI: create, log, inspect a day, edit, share, revoke, archive, restore, delete',async({page,browser})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');await page.getByRole('button',{name:'Create an account',exact:true}).click();
  await page.getByLabel('Your name').fill('Alex');await page.getByLabel('Email',{exact:true}).fill(`ui-${Date.now()}@example.com`);await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Create your journal'}).click();
  await page.getByRole('button',{name:'Create your first track'}).click();
  await page.getByLabel('Name',{exact:true}).fill('German');await page.getByLabel('Description optional').fill('A little closer to fluent.');await page.getByRole('dialog').getByRole('button',{name:'Create track',exact:true}).click();
  await expect(page.getByRole('heading',{name:'German',exact:true})).toBeVisible();
  await page.locator('.card-log').click();await page.getByLabel('Activity',{exact:true}).fill('German lesson');await page.getByLabel('Amount optional').fill('25');await page.getByLabel('Notes optional').fill('Practiced der, die, das.');await page.getByRole('button',{name:'Save activity',exact:true}).click();
  await expect(page.getByText('German lesson',{exact:true})).toBeVisible();
  await page.reload();await expect(page.getByText('German lesson',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Open German',exact:true}).click();
  await page.getByRole('button',{name:`${today}: 1 activity`,exact:true}).click();
  await expect(page.getByRole('button',{name:'Show all activities'})).toBeVisible();
  await page.getByRole('button',{name:'Edit activity',exact:true}).click();await page.getByLabel('Activity',{exact:true}).fill('German lesson and articles');await page.getByRole('button',{name:'Save activity',exact:true}).click();
  await expect(page.getByRole('heading',{name:'German lesson and articles'})).toBeVisible();
  await page.getByRole('button',{name:/Share/}).click();await page.getByRole('button',{name:'Create sharing link'}).click();
  const url=await page.getByLabel('Your read-only link').inputValue();
  const anonymous=await browser.newContext();const shared=await anonymous.newPage();await shared.goto(url);
  await expect(shared.getByRole('heading',{name:'German lesson and articles'})).toBeVisible();await expect(shared.getByRole('button',{name:'Edit activity'})).toHaveCount(0);
  await page.getByRole('button',{name:'Turn off link sharing'}).click();await shared.reload();await expect(shared.getByRole('alert')).toContainText('no longer available');await anonymous.close();
  await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'Edit track',exact:true}).click();await page.getByRole('button',{name:'Archive track',exact:true}).click();
  await expect(page.getByText('ARCHIVED TRACK',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit track',exact:true}).click();await page.getByRole('button',{name:'Restore track',exact:true}).click();
  await page.getByRole('button',{name:'Delete activity',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Delete activity',exact:true}).click();await expect(page.getByRole('heading',{name:'A quiet day.'})).toBeVisible();
  await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'../.local/mobile-track.png',fullPage:true});expect(errors).toEqual([]);
});
