import { test, expect } from '@playwright/test';
import { dateKey } from '../src/app/journal';
import { passwordProof } from '../src/app/password-proof';
test('example journal renders at desktop and mobile sizes',async({page})=>{
  const email=`layout-${Date.now()}@example.com`,password='Layout-Journal-42!';
  const challenge=await (await page.request.post('/api/auth/challenge',{headers:{'X-Tracks-Request':'1'},data:{email,mode:'register'}})).json();
  await page.request.post('/api/auth/register',{headers:{'X-Tracks-Request':'1'},data:{name:'Alex',email,proof:await passwordProof(password,challenge),ticket:challenge.ticket}});
  const seeded=await page.request.post('/api/examples?today='+dateKey(new Date()),{headers:{'X-Tracks-Request':'1'}});expect(seeded.status()).toBe(204);
  for(let i=0;i<16;i++)await page.request.post('/api/projects',{headers:{'X-Tracks-Request':'1'},data:{name:`Extra track ${i+1}`,description:'',icon:'✦',color:'green',archived:false}});
  await page.setViewportSize({width:1440,height:800});await page.goto('/');
  await expect(page.getByRole('heading',{name:'German',exact:true})).toBeVisible();
  await expect(page.locator('.sidebar')).toHaveCSS('position','fixed');
  const tracksNav=page.locator('.sidebar nav[aria-label="Tracks"]');
  await expect(tracksNav).toHaveCSS('overflow-y','auto');
  await expect.poll(()=>tracksNav.evaluate(element=>element.scrollHeight>element.clientHeight)).toBe(true);
  await expect.poll(()=>page.locator('.sidebar-bottom').evaluate(element=>element.getBoundingClientRect().bottom<=innerHeight)).toBe(true);
  await expect(page.locator('.track-grid')).toHaveCSS('display','grid');
  await page.screenshot({path:'../.local/desktop-journal.png',fullPage:true});
  await page.getByRole('button',{name:'Open Running',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your consistency'})).toBeVisible();
  await page.screenshot({path:'../.local/desktop-track.png',fullPage:false});
  await page.setViewportSize({width:390,height:844});await page.goto('/');
  await expect(page.getByRole('heading',{name:'German',exact:true})).toBeVisible();
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'../.local/mobile-journal.png',fullPage:true});
  await page.getByRole('button',{name:'Archived',exact:true}).click();await expect(page.getByRole('heading',{name:'Nothing tucked away yet.'})).toBeVisible();
});
